from easydict import EasyDict as edict

cfg = edict()

cfg.DATASETS = edict()
cfg.DATASETS.DATADIR = "augmented_camus"  # '/path/to/dataset'
cfg.DATASETS.SAVE_DIR = "output/camus/bmaps"  # '/path/to/save'
cfg.DATASETS.PROBE_MODE = "camus"

cfg.TRAIN = edict()
cfg.TRAIN.DIFFUSION = edict()
cfg.TRAIN.DIFFUSION.LEARN_SIGMA = True
cfg.TRAIN.DIFFUSION.NOISE_SCHEDULE = "cosine"
cfg.TRAIN.DIFFUSION.TIMESTEP_RESPACING = ""
cfg.TRAIN.DIFFUSION.USE_KL = False
cfg.TRAIN.DIFFUSION.PREDICT_XSTART = False
cfg.TRAIN.DIFFUSION.RESCALE_TIMESTEPS = False
cfg.TRAIN.DIFFUSION.RESCALE_LEARNED_SIGMAS = False

cfg.TRAIN.DIFFUSION.B_MAP_MIN = 0.97
# or 1 if you want to use the original code, without b_maps

cfg.TRAIN.DIFFUSION.PRESERVE_LENGTH = False
cfg.TRAIN.DIFFUSION.ADD_BUFFER = False
cfg.TRAIN.B_MAP_SCHEDULER_TYPE = "cosine"

cfg.TRAIN.IMG_SIZE = 128  # 256 if you have enough memory
cfg.TRAIN.NUM_CLASSES = 5
cfg.TRAIN.LR = 1e-4
cfg.TRAIN.ATTENTION_RESOLUTIONS = "32,16,8"
cfg.TRAIN.CHANNEL_MULT = None
cfg.TRAIN.DIFFUSION_STEPS = 1000
cfg.TRAIN.SCHEDULE_SAMPLER = "uniform"
cfg.TRAIN.NUM_CHANNELS = 128  # 256
cfg.TRAIN.NUM_HEADS = 1
cfg.TRAIN.NUM_HEADS_UPSAMPLE = -1
cfg.TRAIN.NUM_HEAD_CHANNELS = 64
cfg.TRAIN.NUM_RES_BLOCKS = 2
cfg.TRAIN.RESBLOCK_UPDOWN = True
cfg.TRAIN.USE_SCALE_SHIFT_NORM = True
cfg.TRAIN.USE_CHECKPOINT = True
cfg.TRAIN.CLASS_COND = True
cfg.TRAIN.WEIGHT_DECAY = 1e-3
cfg.TRAIN.LR_ANNEAL_STEPS = 50000
cfg.TRAIN.BATCH_SIZE = 4
cfg.TRAIN.EMA_RATE = "0.9,0.99"
cfg.TRAIN.LOG_INTERVAL = 100
cfg.TRAIN.SAVE_INTERVAL = 2000
cfg.TRAIN.RESUME_CHECKPOINT = (
    None  # optional, if you want to resume training from a checkpoint
)
cfg.TRAIN.USE_NEW_ATTENTION_ORDER = True
cfg.TRAIN.FP16_SCALE_GROWTH = 1e-2
cfg.TRAIN.NUM_WORKERS = 8
cfg.TRAIN.RANDOM_CROP = False
cfg.TRAIN.RANDOM_FLIP = False
cfg.TRAIN.IS_TRAIN = False

cfg.TRAIN.CHECKPOINT_DIR = "output"


cfg.TEST = edict()
cfg.TEST.S = 1.0
cfg.TEST.INFERENCE_ON_TRAIN = True
cfg.TEST.BATCH_SIZE = 4
cfg.TEST.CLIP_DENOISED = True
cfg.TEST.NUM_SAMPLES = 1000
cfg.TEST.RESULTS_DIR = "/path/to/results"
