dataset_path = ""
output_dir = ""
dataset_img_size = 64
dataset_cls_count = 19
train_batch_size = 2
train_ucond_prob = 0.1
max_train_steps = 10
ddp_variance_type = "learned_range"  # ["fixed_small", "fixed_log", "fixed_large", "fixed_large_log", "learned", "learned_range"]
ddp_guidance_scale = 7.5
ddp_training_beta_type = "linear"  # ["linear", "squaredcos_cap_v2"]
ddp_validation_beta_type = "linear"  # ["linear", "squaredcos_cap_v2"]
gradient_accumulation_steps = 1
lambda_vlb = 1e-3
use_8bit_adam = False
optim_weight_decay = 1e-2
optim_max_grad_norm = 1.0
learning_rate = 1e-4
scale_lr = False
lr_scheduler = "cosine"  # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
lr_warmup_steps = 500
mixed_precision = "bf16"  # ["no", "fp16", "bf16"]
val_every_nepochs = 5
val_num_samples = 10
tracker_name = "tensorboard"  # "tensorboard" (default), "wandb" and "comet_ml"
checkpointing_steps = 1000
checkpointing_total_limit = 10
resume_from_checkpoint = "latest"
seed = 42
use_ema = True
debug = False
